CREATE TABLE USERS(id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,name VARCHAR(50),email VARCHAR(100),password VARCHAR(9),regdate TIMESTAMP WITH TIME ZONE DEFAULT NOW());

CREATE TABLE TASKS(tid INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, userid INTEGER References users(id),taskname VARCHAR(50),iscompleted BOOLEAN,created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW());